### ISSUE TITLE
very useful, such project, much interest, wow

### ISSUE THREAD

**Issue by guilhem** [BarthV/kstmz-issue#1]
![image](https://user-images.githubusercontent.com/486876/103642351-4432ec80-4f53-11eb-8848-9d61858bdaa4.png)

**Comment by BarthV** [comment]
This contribution doesn't match our code of conduct.
https://www.contributor-covenant.org/version/2/0/code_of_conduct/

Closing it.

![image](https://user-images.githubusercontent.com/1901955/103643441-ff0fba00-4f54-11eb-80f4-4e45b8b75daf.png)
